server:
  port: 8082

spring:
  application:
    name: confirmation
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    enabled: true
