server:
  port: 8081

spring:
  application:
    name: owner
  datasource:
    username:
    url: jdbc:postgresql://postgres:5432/owner
    password:
  zipkin:
    base-url: http://zipkin:9411

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    enabled: false